In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
air = pd.read_csv("C:\\Users\\Dell\\DataScience\\Kaggle Files\\Creditcard_fraud-master\\air.csv", parse_dates=[['Date', 'Time']])
air.head()

,Date_Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004-03-10 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004-03-10 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004-03-10 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004-03-10 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [3]:
airD = pd.DataFrame(air)
airD

,Date_Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004-03-10 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004-03-10 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004-03-10 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004-03-10 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
5,2004-03-10 23:00:00,1.2,1197,38,4.7,750,89,1337,96,1393,949,11.2,59.2,0.7848
6,2004-03-11 00:00:00,1.2,1185,31,3.6,690,62,1462,77,1333,733,11.3,56.8,0.7603
7,2004-03-11 01:00:00,1.0,1136,31,3.3,672,62,1453,76,1333,730,10.7,60.0,0.7702
8,2004-03-11 02:00:00,0.9,1094,24,2.3,609,45,1579,60,1276,620,10.7,59.7,0.7648
9,2004-03-11 03:00:00,0.6,1010,19,1.7,561,-200,1705,-200,1235,501,10.3,60.2,0.7517
10,2004-03-11 04:00:00,-200.0,1011,14,1.3,527,21,1818,34,1197,445,10.1,60.5,0.7465
11,2004-03-11 05:00:00,0.7,1066,8,1.1,512,16,1918,28,1182,422,11.0,56.2,0.7366
12,2004-03-11 06:00:00,0.7,1052,16,1.6,553,34,1738,48,1221,472,10.5,58.1,0.7353
13,2004-03-11 07:00:00,1.1,1144,29,3.2,667,98,1490,82,1339,730,10.2,59.6,0.7417
14,2004-03-11 08:00:00,2.0,1333,64,8.0,900,174,1136,112,1517,1102,10.8,57.4,0.7408
15,2004-03-11 09:00:00,2.2,1351,87,9.5,960,129,1079,101,1583,1028,10.5,60.6,0.7691
16,2004-03-11 10:00:00,1.7,1233,77,6.3,827,112,1218,98,1446,860,10.8,58.4,0.7552
17,2004-03-11 11:00:00,1.5,1179,43,5.0,762,95,1328,92,1362,671,10.5,57.9,0.7352
18,2004-03-11 12:00:00,1.6,1236,61,5.2,774,104,1301,95,1401,664,9.5,66.8,0.7951
19,2004-03-11 13:00:00,1.9,1286,63,7.3,869,146,1162,112,1537,799,8.3,76.4,0.8393
20,2004-03-11 14:00:00,2.9,1371,164,11.5,1034,207,983,128,1730,1037,8.0,81.1,0.8736
21,2004-03-11 15:00:00,2.2,1310,79,8.8,933,184,1082,126,1647,946,8.3,79.8,0.8778
22,2004-03-11 16:00:00,2.2,1292,95,8.3,912,193,1103,131,1591,957,9.7,71.2,0.8569
23,2004-03-11 17:00:00,2.9,1383,150,11.2,1020,243,1008,135,1719,1104,9.8,67.6,0.8185
24,2004-03-11 18:00:00,4.8,1581,307,20.8,1319,281,799,151,2083,1409,10.3,64.2,0.8065
25,2004-03-11 19:00:00,6.9,1776,461,27.4,1488,383,702,172,2333,1704,9.7,69.3,0.8319
26,2004-03-11 20:00:00,6.1,1640,401,24.0,1404,351,743,165,2191,1654,9.6,67.8,0.8133
27,2004-03-11 21:00:00,3.9,1313,197,12.8,1076,240,957,136,1707,1285,9.1,64.0,0.7419
28,2004-03-11 22:00:00,1.5,965,61,4.7,749,94,1325,85,1333,821,8.2,63.4,0.6905
29,2004-03-11 23:00:00,1.0,913,26,2.6,629,47,1565,53,1252,552,8.2,60.8,0.6657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,2005-04-03 09:00:00,1.2,1022,-200,4.1,715,192,806,118,1004,831,17.8,30.7,0.6205
9328,2005-04-03 10:00:00,1.4,970,-200,3.4,677,166,888,113,931,613,21.1,23.7,0.5875
9329,2005-04-03 11:00:00,1.3,1000,-200,5.3,779,171,805,115,1001,640,24.0,19.3,0.5673
9330,2005-04-03 12:00:00,1.4,996,-200,5.3,781,177,806,124,985,631,26.5,16.4,0.5594
9331,2005-04-03 13:00:00,1.0,928,-200,3.8,701,119,926,86,902,456,28.7,13.7,0.5302
9332,2005-04-03 14:00:00,1.0,933,-200,4.2,722,121,899,87,890,450,28.5,13.1,0.5002
9333,2005-04-03 15:00:00,1.1,956,-200,5.4,783,142,857,100,896,516,30.0,11.1,0.4624
9334,2005-04-03 16:00:00,1.3,968,-200,6.3,826,197,867,132,898,548,29.4,10.4,0.4192
9335,2005-04-03 17:00:00,1.4,953,-200,6.1,817,242,872,156,891,603,28.9,9.9,0.3866
9336,2005-04-03 18:00:00,1.2,1015,-200,4.6,743,190,851,138,981,597,22.8,21.7,0.5945
9337,2005-04-03 19:00:00,2.7,1248,-200,11.1,1018,367,599,181,1289,1167,19.9,33.0,0.7608
9338,2005-04-03 20:00:00,2.5,1180,-200,7.9,894,355,636,187,1200,1372,17.5,40.7,0.8073
9339,2005-04-03 21:00:00,1.5,1102,-200,6.0,812,235,693,158,1178,1042,16.4,46.6,0.8642
9340,2005-04-03 22:00:00,1.6,1116,-200,5.8,803,233,696,153,1173,1055,15.5,49.0,0.8579
9341,2005-04-03 23:00:00,1.2,1100,-200,5.1,769,170,722,128,1147,1049,14.3,52.5,0.8497
9342,2005-04-04 00:00:00,0.9,1012,-200,3.5,683,117,801,93,1073,816,14.2,51.4,0.8275
9343,2005-04-04 01:00:00,0.6,944,-200,1.9,579,70,925,58,1002,598,13.8,51.2,0.8058
9344,2005-04-04 02:00:00,0.5,912,-200,1.5,544,69,959,55,1002,573,12.1,56.3,0.7927
9345,2005-04-04 03:00:00,0.4,887,-200,1.1,508,62,1047,51,974,549,11.3,58.9,0.7888
9346,2005-04-04 04:00:00,-200.0,864,-200,0.8,478,52,1116,43,958,489,11.8,56.0,0.7743
9347,2005-04-04 05:00:00,0.5,888,-200,1.3,528,77,1077,53,987,578,10.4,59.9,0.7550
9348,2005-04-04 06:00:00,1.1,1031,-200,4.4,730,182,760,93,1129,905,9.5,63.1,0.7531
9349,2005-04-04 07:00:00,4.0,1384,-200,17.4,1221,594,470,155,1600,1457,9.7,61.9,0.7446
9350,2005-04-04 08:00:00,5.0,1446,-200,22.4,1362,586,415,174,1777,1705,13.5,48.9,0.7553
9351,2005-04-04 09:00:00,3.9,1297,-200,13.6,1102,523,507,187,1375,1583,18.2,36.3,0.7487
9352,2005-04-04 10:00:00,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568
9353,2005-04-04 11:00:00,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119
9354,2005-04-04 12:00:00,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406
9355,2005-04-04 13:00:00,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139
9356,2005-04-04 14:00:00,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028

In [4]:
airD.isnull().sum()

Date_Time        0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [5]:
airD.dtypes

Date_Time        datetime64[ns]
CO(GT)                  float64
PT08.S1(CO)               int64
NMHC(GT)                  int64
C6H6(GT)                float64
PT08.S2(NMHC)             int64
NOx(GT)                   int64
PT08.S3(NOx)              int64
NO2(GT)                   int64
PT08.S4(NO2)              int64
PT08.S5(O3)               int64
T                       float64
RH                      float64
AH                      float64
dtype: object

In [6]:
pd.options.mode.chained_assignment = None  
cols = airD.columns
cnt = 0
for j in cols:
    for i in range(0,len(airD)):
        if(airD[j][i]==-200):
            airD[j][i] = airD[j][i-1]
print("Done!")

Done!

In [7]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen
#from statsmodels.tsa.vector_ar.vecm import JohansenTestResult
#from johansen import coint_johansen
johan_test_temp = airD.drop(['Date_Time'], axis=1)
coint_johansen(johan_test_temp,0,1).eig

#Eigen values for the lag polynomial must be less than 1, for the data to be multivariate time series stationary: Johansen Test, similar to Dickey Fuller Test.

C:\Users\Dell\Anaconda3\lib\site-packages\statsmodels\tsa\vector_ar\vecm.py:608: HypothesisTestWarning: Critical values are only available for time series with 12 variables at most.
  category=HypothesisTestWarning)

array([0.19849152, 0.15914057, 0.12321066, 0.10731769, 0.09540444,
       0.08325317, 0.06642627, 0.05803392, 0.04035113, 0.03390943,
       0.02782613, 0.00953236, 0.00202889])

In [8]:
airD['Date_Time'] = airD['Date_Time'].values.astype(float)

In [9]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen
df = airD.drop(['Date_Time'], axis=1)
def cointegration_test(df, alpha=0.05): 
    out = coint_johansen(df,-1,1)
    d = {'0.90':0, '0.95':1, '0.99':2}
    traces = out.lr1
    cvts = out.cvt[:, d[str(1-alpha)]]
    def adjust(val, length= 6): return str(val).ljust(length)

    # Summary
    print('Name   ::  Test Stat > C(95%)    =>   Signif  \n', '--'*20)
    for col, trace, cvt in zip(df.columns, traces, cvts):
        print(adjust(col), ':: ', adjust(round(trace,2), 9), ">", adjust(cvt, 8), ' =>  ' , trace > cvt)

cointegration_test(df.astype(float))

Name   ::  Test Stat > C(95%)    =>   Signif
 ----------------------------------------
CO(GT) ::  9113.24   > nan       =>   False
PT08.S1(CO) ::  7336.47   > 311.1288  =>   True
NMHC(GT) ::  5780.43   > 263.2603  =>   True
C6H6(GT) ::  4627.49   > 219.4051  =>   True
PT08.S2(NMHC) ::  3566.39   > 179.5199  =>   True
NOx(GT) ::  2642.34   > 143.6691  =>   True
PT08.S3(NOx) ::  1922.53   > 111.7797  =>   True
NO2(GT) ::  1306.38   > 83.9383   =>   True
PT08.S4(NO2) ::  750.51    > 60.0627   =>   True
PT08.S5(O3) ::  423.38    > 40.1749   =>   True
T      ::  135.39    > 24.2761   =>   True
RH     ::  23.99     > 12.3212   =>   True
AH     ::  0.66      > 4.1296    =>   False

C:\Users\Dell\Anaconda3\lib\site-packages\statsmodels\tsa\vector_ar\vecm.py:608: HypothesisTestWarning: Critical values are only available for time series with 12 variables at most.
  category=HypothesisTestWarning)

In [10]:
train = df[:int(0.8*(len(df)))]
valid = df[int(0.8*(len(df))):]
from statsmodels.tsa.vector_ar.var_model import VAR

model = VAR(endog=train)
model_fit = model.fit()
prediction = model_fit.forecast(model_fit.y, steps=len(valid))
print(prediction)

[[8.87831181e-01 8.41930040e+02 2.71627237e+02 ... 1.05475985e+01
  3.49086438e+01 4.37327493e-01]
 [9.91857261e-01 8.66300135e+02 2.69296720e+02 ... 9.82637273e+00
  3.74495946e+01 4.42716879e-01]
 [1.10418099e+00 8.90877509e+02 2.67701932e+02 ... 9.21409050e+00
  3.96788583e+01 4.47482162e-01]
 ...
 [2.13382383e+00 1.10697508e+03 2.69410699e+02 ... 2.01841814e+01
  4.89013982e+01 1.11131826e+00]
 [2.13382382e+00 1.10697508e+03 2.69410699e+02 ... 2.01841816e+01
  4.89013980e+01 1.11131827e+00]
 [2.13382381e+00 1.10697507e+03 2.69410699e+02 ... 2.01841819e+01
  4.89013978e+01 1.11131829e+00]]

C:\Users\Dell\Anaconda3\lib\site-packages\statsmodels\base\wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)